<?php

// Add github syntax highlighting
// vim: set filetype=php:
// -*- mode: php;-*-

/**
 * Implementation of hook_form_FORM_ID_alter
 * 
 * Add our configuration to the site information form.
 * 
 * @param array $form
 * @param array $form_state
 * @param string $form_id
 */
function hcpss_schoolsite_config_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['hcpss_schoolsite_config'] = array(
    '#type'   => 'fieldset',
    '#title'  => 'HCPSS Schools Site Configuration',
  );
  
  // Add the school code field
  $form['hcpss_schoolsite_config']['hcpss_school_code'] = array(
    '#type'           => 'textfield',
    '#title'          => 'School Code',
    '#default_value'  => variable_get('hcpss_school_code'),
    '#required'       => TRUE,
  );
  
  // Add the facebook URL field
  $form['hcpss_schoolsite_config']['hcpss_school_facebook_url'] = array(
    '#type'             => 'textfield',
    '#title'            => 'Facebook URL',
    '#default_value'    => variable_get('hcpss_school_facebook_url'),
    '#element_validate' => array('_hcpss_schoolsite_config_validate_url'),
  );
}

/**
 * Element validate callback to validate that an element is a valid URL.
 * 
 * @param array $element
 * @param array $form_state
 * @param array $form
 */
function _hcpss_schoolsite_config_validate_url($element, &$form_state, $form) {
  if (!empty($element['#value']) && !valid_url($element['#value'], TRUE)) {
    form_error($element, t('Please enter a valid URL.'));
  }
}

/**
 * Set the site configuration to it's default(s)
 */
function _hcpss_schoolsite_config_set_default_config() {
  // School code
  if (!$code = variable_get('hcpss_school_code')) {
    $code = _hcpss_schoolsite_config_guess_school_code();
    variable_set('hcpss_school_code', $code);
  }
}

/**
 * Guess the school code from the name of the database
 * 
 * @global array $databases
 * @return string
 */
function _hcpss_schoolsite_config_guess_school_code() {
  global $databases;
  
  // If the database name is "site_hs_rhhs" then the code is "rhhs"
  $db_name        = $databases['default']['default']['database'];
  $db_name_array  = explode('_', $db_name);
  $code           = array_pop($db_name_array);
  
  return $code;
}
